src/public/assets/js/custom.js

Update apps on each page refresh

---

LICENSE

add apache 2.0 license file

---

README.md

Typo fix in readme.

---

deployments/kubernetes/chart/forecastle/templates/service.yaml
deployments/kubernetes/chart/forecastle/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

Add xposer annotations

---

deployments/kubernetes/chart/forecastle/values.yaml

Fix xposer annotations

---

deployments/kubernetes/templates/chart/values.yaml.tmpl

Fix values.yaml.tmpl

---

deployments/kubernetes/templates/chart/values.yaml.tmpl

Add quotes around annotations in values.yaml.tmpl

---

deployments/kubernetes/chart/forecastle/values.yaml

by default we should enforce ssl redirect

by default ssl redirect should be true

---

deployments/kubernetes/chart/forecastle/templates/_helpers.tpl
deployments/kubernetes/chart/forecastle/templates/configmap.yaml
deployments/kubernetes/chart/forecastle/templates/deployment.yaml
deployments/kubernetes/chart/forecastle/templates/rbac.yaml
deployments/kubernetes/chart/forecastle/templates/service.yaml

Append chart name

---

README.md
deployments/kubernetes/templates/chart/values.yaml.tmpl
pkg/annotations/annotations.go
pkg/apps/apps.go
pkg/apps/apps_test.go
pkg/apps/filters.go
pkg/apps/filters_test.go
pkg/config/config.go
pkg/handlers/appsHandler.go
pkg/kube/lists/ingresses/ingresses.go
pkg/kube/lists/ingresses/ingresses_test.go
pkg/kube/wrappers/ingress.go
pkg/kube/wrappers/ingress_test.go
static/assets/js/custom.js

Add support for running multiple named instances of forecastle

---

deployments/kubernetes/chart/forecastle/templates/deployment.yaml
deployments/kubernetes/chart/forecastle/templates/ingress.yaml
deployments/kubernetes/chart/forecastle/templates/service.yaml
deployments/kubernetes/chart/forecastle/values.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stakater/forecastle/87)

Fixes 85. Cleanup config and add ingress

---

deployments/kubernetes/chart/forecastle/templates/ingress.yaml
deployments/kubernetes/chart/forecastle/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

Fix helm chart

---

deployments/kubernetes/chart/forecastle/Chart.yaml
deployments/kubernetes/chart/forecastle/templates/deployment.yaml
deployments/kubernetes/chart/forecastle/templates/ingress.yaml
deployments/kubernetes/chart/forecastle/templates/rbac.yaml

* add node-selector
* use .Release.Namespace to bind to correct service-account
* fix error in deployment resource
* fix an error in the ingress when using TLS
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/stakater/forecastle/89)

Fix deployment

---

pkg/forecastle/crdapps/crdapps.go
pkg/forecastle/crdapps/crdapps_test.go

Skip apps with invalid URL references

---

deployments/kubernetes/chart/forecastle/crds/forecastleApp.yaml
deployments/kubernetes/forecastle.yaml
deployments/kubernetes/manifests/crd.yaml

fixed the issue with installing the CRDs to a fresh cluster >=1.21

---

deployments/kubernetes/forecastle.yaml

as pipeline doesn't update jumbo manifest so, updating to working version manually

forcefully update to working version

---

deployments/kubernetes/chart/forecastle/crds/forecastleApp.yaml

Obsoletes https://github.com/stakater/Forecastle/pull/176 and fixes both for route and ingress.
@rasheedamir

Ingress ref crd fix

---

deployments/kubernetes/chart/forecastle/templates/deployment.yaml
deployments/kubernetes/chart/forecastle/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

Some properties are needed in advanced scheduling setups

Add tolerations and affinity

---

deployments/kubernetes/chart/forecastle/templates/ingress.yaml
deployments/kubernetes/chart/forecastle/values.yaml
deployments/kubernetes/templates/chart/values.yaml.tmpl

I take the ingress logic from here:
https://github.com/dexidp/helm-charts/blob/master/charts/dex/templates/ingress.yaml

Support networking.k8s.io/v1 Ingress

---

deployments/kubernetes/chart/forecastle/templates/ingress.yaml

Add ingress class name for k8s 1.18 and above

---

.github/workflows/push.yaml
pkg/handlers/appsHandler.go

Update Push Pipeline

---

.github/workflows/pull_request.yaml
deployments/kubernetes/chart/forecastle/templates/deployment.yaml
deployments/kubernetes/chart/forecastle/values.yaml

Add support for resources

---

.github/workflows/release.yaml

Missed the update of the action in this WF too.

use correct action version to use updated param

---

.github/workflows/pull_request.yaml
.github/workflows/push.yaml
Dockerfile
go.mod

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

Upgrade golang to 1.19

---

deployments/kubernetes/chart/forecastle/templates/rbac.yaml

Adds namesapce to ServiceAccount

Adds namesapce to ServiceAccount

---

.github/workflows/push.yaml

Fix broken tagging due to: https://github.com/anothrNick/github-tag-action/pull/230
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

Fix tagging action

---

deployments/kubernetes/chart/forecastle/templates/deployment.yaml
deployments/kubernetes/chart/forecastle/values.yaml

Addition was tested and seems to be working, please review and accept the proposed changes
10x,
Tiran Meltser.

Add support for customizing imagePullSecrets

---

frontend/package.json
frontend/src/redux/app/appsModule.js
frontend/src/redux/app/configModule.js
frontend/src/redux/filters/filtersModule.js
frontend/src/redux/index.js
frontend/yarn.lock

- Replaced package `redux-starter-kit` to `@reduxjs/toolkit` as it has been renamed.
- Replaced the `slice` field with `name` in `createSlice` config.

Fix Redux Toolkit error

---

README.md

This PR introduces several improvements to the Forecastle README file. The goal is to enhance clarity, user accessibility, and overall readability. These changes are designed to make the README more intuitive and informative, particularly for new users or those unfamiliar with Forecastle.

Enhancements to README for Improved Clarity and Usability

---

frontend/src/components/SearchAppBar/SearchAppBar.js

fixes https://github.com/stakater/Forecastle/issues/172
Tested in my lab. 
Docker image: `ghcr.io/aslafy-z/forecastle/forecastle:update-title-2`

feat: set page title to configured title

---

README.md

Fixes https://github.com/stakater/Forecastle/issues/398

docs: update helm chart section
